export const FETCH_EMPLOYEE_COMMENCEMENTS = 'FETCH_EMPLOYEE_COMMENCEMENTS'
export const SAVE_EMPLOYEE_COMMENCEMENT = 'SAVE_EMPLOYEE_COMMENCEMENT'
export const UPDATE_EMPLOYEE_COMMENCEMENT = 'UPDATE_EMPLOYEE_COMMENCEMENT'
