export const FETCH_INCOME_PARTICULARS = 'FETCH_INCOME_PARTICULARS'
// export const UPDATE_INCOME_PARTICULARS = 'UPDATE_INCOME_PARTICULARS'
// export const UPDATE_INCOME_PARTICULAR_PAYTYPES = 'UPDATE_INCOME_PARTICULAR_PAYTYPE'
