export const GENERATE_IRD_REQUEST_FORM = 'GENERATE_IRD_REQUEST_FORM'
export const TERMINATE_IRD_REQUEST_FORM_GENERATION = 'TERMINATE_IRD_REQUEST_FORM_GENERATION'
export const UPDATE_APPROVAL_REQUEST_FORM = 'UPDATE_APPROVAL_REQUEST_FORM'
export const FETCH_SAMPLE_FORM = 'FETCH_SAMPLE_FORM'
