export const FETCH_FORM_RECORD = 'FETCH_FORM_RECORD'
export const SAVE_FORM_RECORD = 'SAVE_FORM_RECORD'
export const UPDATE_FORM_RECORD = 'UPDATE_FORM_RECORD'
export const REMOVE_FORM_RECORD = 'REMOVE_FORM_RECORD'
