export const FETCH_IR56B_INCOMES = 'FETCH_IR56B_INCOMES'
export const FETCH_IR56F_INCOMES = 'FETCH_IR56F_INCOMES'
// export const UPDATE_INCOME_PARTICULARS = 'UPDATE_INCOME_PARTICULARS'
// export const UPDATE_INCOME_PARTICULAR_PAYTYPES = 'UPDATE_INCOME_PARTICULAR_PAYTYPE'
