export const FETCH_TEAMS = 'FETCH_TEAMS'
export const FETCH_TEAM = 'FETCH_TEAM'
export const SET_TEAMS = 'SET_TEAMS'
export const FETCH_TEAM_INFO = 'FETCH_TEAM_INFO'
export const UPDATE_TEAMS = 'UPDATE_TEAMS'
export const FETCH_APP_TEAMS = 'FETCH_APP_TEAMS'
