// GROUPS
export const FETCH_OA_GROUPS = 'FETCH_OA_GROUPS'

export const CLEAR_GROUP_SELECTION = 'CLEAR_GROUP_SELECTION'
export const SELECT_GROUP = 'SELECT_GROUP'
export const CLEAR_GROUP_EMPLOYEE_SELECTION = 'CLEAR_GROUP_EMPLOYEE_SELECTION'
export const SELECT_ALL_GROUP_EMPLOYEES = 'SELECT_ALL_GROUP_EMPLOYEES'

// EMPLOYEES
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES'

export const SELECT_EMPLOYEE = 'SELECT_EMPLOYEE'
export const SELECT_ALL_EMPLOYEES = 'SELECT_ALL_EMPLOYEES'
export const CLEAR_EMPLOYEE_SELECTION = 'CLEAR_EMPLOYEE_SELECTION'
export const TOGGLE_EMPLOYEE_SELECTION = 'TOGGLE_EMPLOYEE_SELECTION'
export const TOGGLE_TO_EMPLOYEE = 'TOGGLE_TO_EMPLOYEE'
export const SET_ACTIVE_EMPLOYEE_ID = 'SET_ACTIVE_EMPLOYEE_ID'
export const SET_HOVERING_EMPLOYEE_ID_ACTIVE = 'SET_HOVERING_EMPLOYEE_ID_ACTIVE'
